# Generated by Django 4.0.1 on 2022-02-01 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lineas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pasajero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.DateTimeField()),
                ('hora_salida', models.DateTimeField()),
                ('estacion_entrada', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estacionentrada', to='lineas.estacion')),
                ('estacion_salida', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estacionsalida', to='lineas.estacion')),
                ('pasajero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lineas.pasajero')),
            ],
        ),
    ]
