# Generated by Django 4.0.1 on 2022-02-01 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lineas', '0002_pasajero_viaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='estacion_entrada',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas', to='lineas.estacion'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='estacion_salida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salidas', to='lineas.estacion'),
        ),
    ]
